apiVersion: v1
kind: ConfigMap
metadata:
  name: astro-ui-configmap
data:
  NEAR_ENV: "{{ .Values.environment.near_env }}"
  NEAR_CONTRACT_NAME: "{{ .Values.environment.near_contract_name }}"
  API_URL: "{{ .Values.environment.api_url }}"
  AWS_BUCKET: "{{ .Values.environment.aws_bucket }}"
  AWS_REGION: "{{ .Values.environment.aws_region }}"
  AWS_IDENTITY_POOL_ID: "{{ .Values.environment.aws_identity_pool_id }}"
  GOOGLE_ANALYTICS_KEY: "{{ .Values.environment.google_analytics_key }}"
  STATS_API_URL: "{{ .Values.environment.stats_api_url }}"
  NEXT_PUBLIC_LAUNCHDARKLY_ID: "{{ .Values.environment.next_public_launchdarkly_id }}"
